spring:
  application:
    name: share-photo-config
  boot:
    admin:
      client:
        url: http://localhost:7010
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/JoherYu/socail-network-microservice
          search-paths: /BackEnd/SharePhoto-config/repos
          username: 
          password:
  zipkin:
    base-url: http://localhost:7020

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
