spring:
  application:
    name: share-photo-zuul
  zipkin:
    base-url: http://localhost:7020
  boot:
    admin:
      client:
        url: http://localhost:7010

server:
  port: 7030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts