spring:
  application:
    name: share-photo-zuul
  zipkin:
    base-url: http://localhost:7020
  boot:
    admin:
      client:
        url: http://localhost:7010

server:
  port: 7030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

zuul:
  routes:
    login:
      path: /session
      serviceId: share-photo-sso