spring:
  application:
    name: share-photo-eureka
  zipkin:
    base-url: http://localhost:7020

server:
  port: 7010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info