spring:
  application:
    name: share-photo-admin
  zipkin:
    base-url: http://39.106.36.194:7020

server:
  port: 7010

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.36.194:7000/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info