version: '3.1'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=replicas_db"
    links:
      - mysql-slave-1
      - mysql-slave-2
    ports:
      - "3306:3306"
    restart: always
    hostname: mysql-master
  mysql-slave-1:
    build:
      context: ./
      dockerfile: slave1/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=replicas_db"
    ports:
      - "3307:3306"
    restart: always
    hostname: mysql-slave-1
  mysql-slave-2:
    build:
      context: ./
      dockerfile: slave2/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=replicas_db"
    ports:
      - "3308:3306"
    restart: always
    hostname: mysql-slave-2

